spring:
  cloud:
    gateway:
      routes:
        - id: movie_service
          uri: http://localhost:8081
          predicates:
            - Path=/movies/**
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: rating_service
          uri: http://localhost:8083
          predicates:
            - Path=/ratings/**
      discovery:
        locator:
          enabled: true
