server:
  port: 8080 # Gateway servisi için port

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: film-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/films/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**, /auth/**
        - id: comment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/comments/**
      default-filters:
        - AddResponseHeader=X-Gateway-Header, Gateway-Service
    security:
      enabled: true # Spring Security entegrasyonu varsa kullanılır
